site_name: Daniel Panea
site_description: Explore AI and intelligent automations with Daniel Panea
site_url: https://danielpanea.com

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.keys


nav:
  - Home: index.md
  - Case Studies: 
    - portfolio/index.md
    - portfolio/projects/project-1.md
    - portfolio/projects/project-2.md
    - portfolio/projects/project-3.md


theme:
  name: material
  features:
    - search.suggest
    - toc.integrate
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - navigation.footer
  language: en
  palette:
    - scheme: danielpanea
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom  
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  # icon:
  #   logo: mylogo
  logo: assets/mylogo_cropped.png
  favicon: assets/mylogo.svg

extra:
  generator: true
  social:
    # - icon: fontawesome/solid/building
    #   link: https://company.com
    - icon: fontawesome/brands/github
      link: https://github.com/dpanea
    # - icon: fontawesome/brands/youtube
    #   link: https://youtube.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniel-panea-lichtig
  analytics:
    # provider: google
    # property: G-W9Y130NXVZ

extra_css:
  - stylesheets/extra.css
  - stylesheets/hero.css
plugins:
  - search
  - awesome-pages
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: 🇺🇸 English
          build: true
        - locale: es
          name: 🇪🇸 Español
          build: true
        - locale: de
          name: 🇩🇪 Deutsch
          build: true
  - social:
      cards_layout_options:
        background_color: "#111111"
  # - blog:
  #     blog_dir: blog
  #     authors_file: "{blog}/.authors.yml"
  #     categories: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js

copyright: |
  &copy; 2025 <a href="https://www.linkedin.com/in/daniel-panea-lichtig" target="_blank" rel="noopener">Daniel Panea</a>. All rights reserved.