[project]
name = "mkdocs-website-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-awesome-pages-plugin>=2.10.1",
    "mkdocs-material[imaging]>=9.6.9",
    "mkdocs-static-i18n>=1.3.0",
]
